- hosts: frontend
  roles:
    - role: frontend
      vars:
        image: "fernandofalla/frontend:1.00"
        ports: "5173:5173"

- hosts: microservices
  roles:
    - role: microservices
      vars:
        services:
          - name: "clima"
            image: "fernandofalla/weather:1.0"
            ports: "5000:5000"
          - name: "temperatura"
            image: "fernandofalla/temperature:1.0"
            ports: "5001:5001"
          - name: "calidad_aire"
            image: "fernandofalla/aqi:1.0"
            ports: "5002:5002"